### ISSUE TITLE
Feature Request - Speech Detection and Translation

### ISSUE THREAD

**Issue by theiturhs** [bishalde/Translatekor#7]
As a GSSOC'24 contributor to the FullStack Translator Application, I propose the implementation of a new feature that enables speech detection and translation. It can allow users to speak and then automatically detect the source language, and then translate the spoken text into the desired target language.

**Comment by bishalde** [comment]
Thanyou @theiturhs  Sure, you can proceed with it.!

Create  a new branch, push the changes in that branch!

And feel free to give this Repository a STAR⭐ and follow back 😊.
